{{ config(
    materialized='table',
    post_hook=[
      'create index if not exists idx_' ~ this.identifier ~ '__year_month on ' ~ this ~ ' (year, month)',
      'create index if not exists idx_' ~ this.identifier ~ '__county_year_month on ' ~ this ~ ' (county, year, month)',
      'create index if not exists idx_' ~ this.identifier ~ '__subcounty_year_month on ' ~ this ~ ' (sub_county, year, month)'
    ]
) }}
select
    "county" as county,
    "Sub County" as sub_county,
    "Period" as period,
    to_char(to_date("Period", 'Month YYYY'), 'MM') as month,
    to_char(to_date("Period", 'Month YYYY'), 'YYYY') as year,
    "Abortion <5 yrs",
    "Abortion >5 yrs",
    "All other diseases <5 yrs",
    "All other diseases >5 yrs",
    "Anaemia cases <5 yrs",
    "Anaemia cases >5 yrs",
    "Arthritis, Joint pains etc. <5 yrs",
    "Arthritis, Joint pains etc. >5 yrs",
    "Asthma <5 yrs",
    "Asthma >5 yrs",
    "Autism <5 yrs",
    "Autism >5 yrs",
    "Bilharzia (Schistosomiasis) <5 yrs",
    "Bilharzia (Schistosomiasis) >5 yrs",
    "Brucellosis <5 yrs",
    "Brucellosis >5 yrs",
    "Burns <5 yrs",
    "Burns >5 yrs",
    "Cardiovascular conditions <5 yrs",
    "Cardiovascular conditions >5 yrs",
    "Central Nervous System Conditions <5 yrs",
    "Central Nervous System Conditions >5 yrs",
    "Cerebral Palsy <5 yrs",
    "Cerebral Palsy >5 yrs",
    "Chicken Pox <5 yrs",
    "Chicken Pox >5 yrs",
    "Cholera <5 yrs",
    "Cholera >5 yrs",
    "Confirmed Malaria (only Positive cases) <5 yrs",
    "Confirmed Malaria (only Positive cases) >5 yrs",
    "Deaths due to Road Traffic Injuries <5 yrs",
    "Deaths due to Road Traffic Injuries >5 yrs",
    "Dental Disorders <5 yrs",
    "Dental Disorders >5 yrs",
    "Diabetes <5 yrs",
    "Diabetes >5 yrs",
    "Diarrhoea <5 yrs",
    "Diarrhoea >5 yrs",
    "Disease of Puerperium and Childbirth <5 yrs",
    "Disease of Puerperium and Childbirth >5 yrs",
    "Disease of the skin <5 yrs",
    "Disease of the skin >5 yrs",
    "Dog Bites <5 yrs",
    "Dog Bites >5 yrs",
    "Down's syndromes <5 yrs",
    "Down's syndromes >5 yrs",
    "Dysentery (Bloody Diarrhoea) <5 yrs",
    "Dysentery (Bloody Diarrhoea) >5 yrs",
    "Ear Infections/ Conditions <5 yrs",
    "Ear Infections/ Conditions >5 yrs",
    "Epilepsy <5 yrs",
    "Epilepsy >5 yrs",
    "Eye Infections <5 yrs",
    "Eye Infections >5 yrs",
    "Fistula (Birth related) <5 yrs",
    "Fistula (Birth related) >5 yrs",
    "Hepatitis <5 yrs",
    "Hepatitis >5 yrs",
    "Hypertension <5 yrs",
    "Hypertension >5 yrs",
    "Intestinal worms <5 yrs",
    "Intestinal worms >5 yrs",
    "Jiggers Infestation <5 yrs",
    "Jiggers Infestation >5 yrs",
    "Leishmaniaisis(Kalazar) <5 yrs",
    "Leishmaniaisis(Kalazar) >5 yrs",
    "Amoebiasis <5 yrs",
    "Amoebiasis >5 yrs",
    "Chikungunya <5 yrs",
    "Chikungunya >5 yrs",
    "Cutaneous leishmaniasis <5 yrs",
    "Cutaneous leishmaniasis >5 yrs",
    "Dengue fever <5 yrs",
    "Dengue fever >5 yrs",
    "Diarrhoea with severe dehydration <5 yrs",
    "Diarrhoea with severe dehydration >5 yrs",
    "Diarrhoea with some dehydration <5 yrs",
    "Diarrhoea with some dehydration >5 yrs",
    "Down's syndrome <5 yrs",
    "Down's syndrome >5 yrs",
    "Gastroenterirtis <5 yrs",
    "Gastroenterirtis >5 yrs",
    "Hypoxaemia (Spo2<90%) <5 yrs",
    "Hypoxaemia (Spo2<90%) >5 yrs",
    "Lower Respiratory Tract Infections <5 yrs",
    "Lower Respiratory Tract Infections >5 yrs",
    "Neonatal Sepsis <5 yrs",
    "Neonatal Sepsis >5 yrs",
    "Pneumonia <5 yrs",
    "Pneumonia >5 yrs",
    "Rev 2020 Pneumonia <5 yrs",
    "Rev 2020 Pneumonia >5 yrs",
    "Rheumatic Fever <5 yrs",
    "Rheumatic Fever >5 yrs",
    "Rift valley fever <5 yrs",
    "Rift valley fever >5 yrs",
    "Severe pneumonia <5 yrs",
    "Severe pneumonia >5 yrs",
    "Suspected Childhood Cancers <5 yrs",
    "Suspected Childhood Cancers >5 yrs",
    "Suspected anthrax <5 yrs",
    "Suspected anthrax >5 yrs",
    "Tested for Malaria <5 yrs",
    "Tested for Malaria >5 yrs",
    "Diarrhoea with no dehydration <5 yrs",
    "Diarrhoea with no dehydration >5 yrs",
    "Malaria in pregnancy <5 yrs",
    "Malaria in pregnancy >5 yrs",
    "Malnutrition <5 yrs",
    "Malnutrition >5 yrs",
    "Measles <5 yrs",
    "Measles >5 yrs",
    "Meningococcal Meningitis <5 yrs",
    "Meningococcal Meningitis >5 yrs",
    "Mental Disorders <5 yrs",
    "Mental Disorders >5 yrs",
    "Mumps <5 yrs",
    "Mumps >5 yrs",
    "Muscular skeletal conditions <5 yrs",
    "Muscular skeletal conditions >5 yrs",
    "Neonatal Tetanus <5 yrs",
    "Neonatal Tetanus >5 yrs",
    "Neoplasms <5 yrs",
    "Neoplasms >5 yrs",
    "Other Dis. Of Respiratory System <5 yrs",
    "Other Dis. Of Respiratory System >5 yrs",
    "Other Bites <5 yrs",
    "Other Bites >5 yrs",
    "Other Central Nervous System Conditions <5 yrs",
    "Other Central Nervous System Conditions >5 yrs",
    "Other Convulsive Disorders <5 yrs",
    "Other Convulsive Disorders >5 yrs",
    "Other Eye conditions <5 yrs",
    "Other Eye conditions >5 yrs",
    "Other Meningitis <5 yrs",
    "Other Meningitis >5 yrs",
    "Other injuries <5 yrs",
    "Other injuries >5 yrs",
    "Overweight (BMI >25) <5 yrs",
    "Overweight (BMI >25) >5 yrs",
    "Physical Disability <5 yrs",
    "Physical Disability >5 yrs",
    "Plague <5 yrs",
    "Plague >5 yrs",
    "Poisoning <5 yrs",
    "Poisoning >5 yrs",
    "Poliomyelitis (AFP) <5 yrs",
    "Poliomyelitis (AFP) >5 yrs",
    "Presumed Tuberculosis <5 yrs",
    "Presumed Tuberculosis >5 yrs",
    "Referrals from Community Unit <5 yrs",
    "Referrals from Community Unit >5 yrs",
    "Referrals to Community Unit <5 yrs",
    "Referrals to Community Unit >5 yrs",
    "Rickets <5 yrs",
    "Rickets >5 yrs",
    "Road Traffic Injuries <5 yrs",
    "Road Traffic Injuries >5 yrs",
    "Sexual Violence <5 yrs",
    "Sexual Violence >5 yrs",
    "Sexually Transmitted Infections <5 yrs",
    "Sexually Transmitted Infections >5 yrs",
    "Snake Bites <5 yrs",
    "Snake Bites >5 yrs",
    "Suspected Malaria <5 yrs",
    "Suspected Malaria >5 yrs",
    "Tetanus <5 yrs",
    "Tetanus >5 yrs",
    "Tonsilitis <5 yrs",
    "Tonsilitis >5 yrs",
    "Tryponosomiasis <5 yrs",
    "Tryponosomiasis >5 yrs",
    "Typhoid fever <5 yrs",
    "Typhoid fever >5 yrs",
    "Upper Respiratory Tract Infections <5 yrs",
    "Upper Respiratory Tract Infections >5 yrs",
    "Urinary Tract Infection <5 yrs",
    "Urinary Tract Infection >5 yrs",
    "Violence related injuries <5 yrs",
    "Violence related injuries >5 yrs",
    "Viral Haemorrhagic Fever <5 yrs",
    "Viral Haemorrhagic Fever >5 yrs",
    "Yellow fever cases <5 yrs",
    "Yellow fever cases >5 yrs"

from {{ source("central_raw_khis", "moh_705") }}
